Home : Acceuil
News : Fil d’actualité
Calendar : Calendrier
Files : Documents et formulaires
Theme : Changer de thème
Profile : Profil
Login : Connexion
Logout : Deconnexion
Inscriptions : inscriptions
MemberZone : Zone Membres
Links : Liens
OtherLanguage : de

NotAnAdmin: You must be an administrator to access this page.

WelcomeHomepage: Welcome to the homepage
SeeArchive: See the archive

NoEntries: There are no entries in the blog
LoginToPost: Admins can login to post
NewEntry: Post to blog
NewEntryTitle: Title
NewEntryContent: Content

PleaseCorrectEntry: Your submitted entry had some errors, please correct and try again.
EntryCreated title@Text: Your new blog post, #{title}, has been created

EntryTitle title@Text: Blog post: #{title}

HomepageTitle: Yesod Blog Demo
NewsArchiveTitle: Blog Archive

